# Generated by Django 3.1.6 on 2021-02-09 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=150, verbose_name='Dni')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('state_existente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BienRaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=150, verbose_name='Dirección')),
                ('TipoInmueble', models.CharField(max_length=150, verbose_name='Tipo de inmueble')),
                ('Pisos', models.IntegerField(default=0, verbose_name='Pisos del inmueble')),
                ('metrado', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('dueño', models.ManyToManyField(to='core.Persons')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'inmueble',
                'ordering': ['id'],
            },
        ),
    ]
