# Generated by Django 3.1.6 on 2021-02-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección Inmueble')),
                ('TipoInmueble', models.CharField(max_length=150, verbose_name='Tipo de inmueble')),
                ('Estado', models.CharField(max_length=150, verbose_name='Vendido o no')),
                ('Pisos', models.PositiveIntegerField(default=0, verbose_name='Cantidad de pisos')),
                ('PrecioTotalBase', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio base del inmueble')),
                ('PrecioTotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio Total')),
                ('cantidadMetrado', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Cantidad de metrado')),
                ('PrecioMetro', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio por metro cuadrado')),
                ('PrecioVenta', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Precio de Venta')),
                ('tamañoBase', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Tamaño de Base')),
                ('tamañoAlto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Tamaño de alto')),
                ('observacion', models.CharField(max_length=1200, verbose_name='Observaciones')),
                ('Referencias', models.CharField(max_length=1200, verbose_name='Referencias')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'inmueble',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='persons',
            name='names',
        ),
        migrations.AddField(
            model_name='persons',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='persons',
            name='name',
            field=models.CharField(default='', editable=False, max_length=250, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='persons',
            name='telefono1',
            field=models.CharField(default='', editable=False, max_length=12, verbose_name='telefono'),
        ),
        migrations.AddField(
            model_name='persons',
            name='telefono2',
            field=models.CharField(default='', editable=False, max_length=12, verbose_name='telefono 2'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='Dni'),
        ),
        migrations.DeleteModel(
            name='BienRaiz',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons'),
        ),
    ]
