# Generated by Django 3.1.6 on 2021-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210209_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='telefono1',
            field=models.CharField(default='', max_length=12, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='telefono2',
            field=models.CharField(default='', max_length=12, verbose_name='telefono 2'),
        ),
    ]
